language: node_js

node_js:
  - 'lts/*'

services:
  - postgresql

env:
  - DB_USER=igekybyt DB_HOST=otto.db.elephantsql.com (otto-01) DB_DATABASE=igekybyt DB_PW=bq3Fh6DILuXf7TVJqSSXIeGXGSBzncdo DB_PORT=5432 SECRET_KEY=bubbagumpshrimp EXPIRY_SECONDS=604800 PORT=3000

cache:
  directories:
    - "$HOME/.npm"

notifications:
  email:
    on_failure: never
