language: node_js
node_js:
  - 'lts/*'
services:
  - postgresql
addons:
  postgresql: "11.3"
env:
  - DATABASE_URL=postgres://postgres:Tope1711@127.0.0.1:5432/api SECRET_KEY=bubbagumpshrimp
cache:
  directories:
    - "$HOME/.npm"