language: node_js
node_js:
  - 'lts/*'
services:
  - postgresql
addons:
  postgresql: "11.3"
env:
  - DATABASE_URL = postgres://postgres:Tope1711@127.0.0.1:5432/api SECRET_KEY = bubbagumpshrimp EXPIRY_SECONDS = 604800
before_script:
  - psql -c 'create database api;' -U postgres
  - psql -c "CREATE USER kay WITH PASSWORD bar;" -U postgres
cache:
  directories:
    - "$HOME/.npm"