language: node_js

node_js:
  - 'lts/*'

addons:
  postgresql: "11.3"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433 DB_USER=postgres DB_HOST=localhost DB_DATABASE=api DB_PW=Tope1711 DB_PORT=5432 SECRET_KEY=bubbagumpshrimp EXPIRY_SECONDS=604800 PORT=3000

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE api;' -U postgres

cache:
  directories:
    - "$HOME/.npm"

notifications:
  email:
    on_failure: never
