language: node_js

node_js:
  - 'lts/*'

env:
  - DB_USER=postgres DB_HOST=localhost DB_DATABASE=api DB_PW=Tope1711 DB_PORT=5432 SECRET_KEY=bubbagumpshrimp EXPIRY_SECONDS=604800 PORT=3000

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE api;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'ci';" -U postgres
  - psql -c "CREATE TABLE users;" -U api

services:
  - postgresql

addons:
  - postgresql: "11.3"

cache:
  directories:
    - "$HOME/.npm"

notifications:
  email:
    on_failure: never
