language: node_js
node_js:
  - 'lts/*'
services:
  - postgresql
addons:
  postgresql: "11.3"
env:
  global:
  - NODE_ENV=test
before_script:
  - psql -c 'create database book_test;' -U postgres
  - psql -c "CREATE USER kay WITH PASSWORD bar;" -U postgres
cache:
  directories:
    - "$HOME/.npm"