language: node_js
services:
  - postgresql
env:
  - DB=postgres://postgres@localhost/api
node_js:
  - 'node'
before_script:
  - psql -c 'create DATABASE api;' -U postgres
  - psql -c "CREATE USER kay WITH PASSWORD 'olu';" -U postgres
cache:
  directories:
    - "node_modules"