language: node_js
services:
  - postgresql
node_js:
  - 'node'
before_script:
  - psql -c 'create database api;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'Tope1711';" -U postgres
cache:
  directories:
    - "$HOME/.npm"