language: node_js

node_js:
  - 'lts/*'

services:
  - postgresql

addons:
  - postgresql: "11"

env:
  - DB_USER=postgres DB_HOST=localhost DB_DATABASE=api DB_PW=Tope1711 DB_PORT=5432 SECRET_KEY=bubbagumpshrimp EXPIRY_SECONDS=604800 PORT=3000

cache:
  directories:
    - "$HOME/.npm"

notifications:
  email:
    on_failure: never
