language: node_js

node_js:
  - 'lts/*'

services:
  - postgresql

addons:
  postgresql: "11.3"

env:
  - DATABASE_URL=postgres://postgres:Tope1711@localhost:5432/api SECRET_KEY=bubbagumpshrimp EXPIRY_SECONDS=604800 PORT=3000

before_script:
  - psql --V
  - cp database.yml.travis database.yml

cache:
  directories:
    - "$HOME/.npm"

notifications:
  email:
    on_failure: never
