language: node_js

node_js:
  - 'lts/*'

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE api;' -U postgres

after_success: npm run coverage

script: npm run travis-test

cache:
  directories:
    - "$HOME/.npm"

notifications:
  email:
    on_failure: never
