language: node_js

node_js:
  - 'lts/*'

services:
  - postgresql

addons:
  - postgresql: "11.3"

env:
  - DB_USER=postgres DB_HOST=localhost DB_DATABASE=api DB_PW=Tope1711 DB_PORT=5432 SECRET_KEY=bubbagumpshrimp EXPIRY_SECONDS=604800 PORT=3000

before_install:
  - sudo apt-get update
  - sudo apt-get
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11 
before_script:
  - psql --version
  - psql -c 'create database api;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'ci';" -U postgres

cache:
  directories:
    - "$HOME/.npm"

notifications:
  email:
    on_failure: never
