language: node_js

node_js:
  - 'lts/*'

addons:
  postgresql: "11.3"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433 

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE api;' -U postgres

cache:
  directories:
    - "$HOME/.npm"

notifications:
  email:
    on_failure: never
